#Resource Icon, 1, ".\GFX\wegweiser.ico"
#Resource Manifest, 1, "SortFilesByDate.exe.manifest"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Sort files"
#Resource Version$ "LegalCopyright",   "Copyright 2017-2018 BasicAware"
#Resource Version$ "OriginalFilename", "SortFileByDate.exe"
#Resource Version$ "ProductName",      "SortFileByDate"
#Resource Version$ "ProductVersion",   "1.0.3.0"
#Resource Version$ "FileVersion",      "1.0.3.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
